# .github/workflows/main.yml
name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Estas se instalarán desde requirements.txt, pero no está de más listarlas aquí
        # para recordar que son necesarias para el despliegue.
        # pip install gunicorn dj-database-url whitenoise 
        # pip install pytest-django # Ya debería estar en requirements.txt

    - name: Run Django migrations (CI check only)
      run: |
        python manage.py check # Corre las comprobaciones de Django
        # No corremos migrate aquí porque no tenemos una DB de test/producción real en el CI para migrar
        # Esto es más para asegurar que el modelo es consistente.

    - name: Run tests
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY_CI || 'una_clave_secreta_dummy_para_ci' }}
        EXCHANGE_RATE_API_KEY: ${{ secrets.EXCHANGE_RATE_API_KEY }}
        DJANGO_SETTINGS_MODULE: core.settings
      run: |
        pytest # Ejecuta tus pruebas de pytest

    - name: Deploy to Railway
      if: success()
      run: |
        curl -fsSL https://railway.app/install.sh | sh # Instala la CLI de Railway
        railway login --token ${{ secrets.RAILWAY_TOKEN }} # Inicia sesión en Railway
        railway link ${{ secrets.RAILWAY_PROJECT_ID }} --service ${{ secrets.RAILWAY_SERVICE_ID }} # Vincula a tu proyecto/servicio
        railway deploy --service ${{ secrets.RAILWAY_SERVICE_ID }} # Despliega
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
